### PR TITLE
fix export for query-flow

### LINKED ISSUE #2239: Fix export
query flow export is not working, likely is related to from pin usage

### PR DESCRIPTION
**Pull request by mason-fish**
fixes #2239 

Get poolId from query source instead of location during query-flow

### CODE REVIEW

File: src/js/flows/exportResults.ts [hunk 1]
```diff
@@ -37,17 +38,26 @@ export default (
...
+    if (span) {
+      const dates = span.map(brim.time).map((t) => t.toDate())
+      from = dates[0]
+      to = dates[1]
+    }
+  }
 
-  dispatch(SystemTest.hook("export-start"))
   const query = annotateQuery(program, {from, to, poolId})
+  dispatch(SystemTest.hook("export-start"))
```
Comment (jameskerr) [inline src/js/flows/exportResults.ts:60]: We can delete all these by the way.

**Review by jameskerr — APPROVED** [review]
