### PR TITLE
fix quotes for brimcap cli args

### LINKED ISSUE #1597: "brimcap search" command line tripped up by paths containing space chars
Repro is with the nightly build [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-60788403.0/macos/Brim-0.25.0-prerelease-60788403.0.dmg,](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-60788403.0/macos/Brim-0.25.0-prerelease-60788403.0.dmg,) hence Brim commit 6078840 which talks to `zed` commit `aa4170e`.

If I open the attached [hello.pcapng.gz](https://github.com/brimdata/brim/files/6408136/hello.pcapng.gz) (after uncompressing), then attempt to click the shark fin to extract a flow from it, I'm shown the "Error preparing pcap" pop-up.

image

As shown in the Dev Tools, the problem seems to be a simple case of the pathname not being quoted and hence the space character in `Application Support` is truncating the path.

```
Error: Command failed: /Applications/Brim.app/Contents/Resources/app.asar.unpacked/zdeps/brimcap search -dst.ip 54.210.89.192 -dst.port 443 -duration 0.293493s -proto tcp -root /Users/phil/Library/Application Support/Brim/data/brimcap-root -src.ip 192.168.10.120 -src.port 63342 -ts 2020-03-09T17:27:53.399273000Z -w /var/folders/yn/jbkxxkpd4vg142pc3_bd_krc0000gn/T/packets-1583774873.399273.pcap
{"type":"error","error":"stat /Users/phil/Library/Application: no such file or directory"}
```

### PR DESCRIPTION
**Pull request by mason-fish**
fixes #1597 

Signed-off-by: Mason Fish <mason@looky.cloud>

### CODE REVIEW

**Review by jameskerr — APPROVED** [review]

File: plugins/brimcap/brimcap-cli.ts [hunk 1]
```diff
@@ -63,10 +63,13 @@ export default class BrimcapCLI {
...
     const commandWithArgs = [
-      this.binPath,
+      `"${this.binPath}"`,
       subCommand,
       ...flatMap(
-        Object.entries(opts).map(([k, v]) => [`-${OPTION_NAME_MAP[k] || k}`, v])
+        Object.entries(opts).map(([k, v]) => [
+          `-${OPTION_NAME_MAP[k] || k}`,
+          `"${v}"`
+        ])
```
Comment (nwt) [inline plugins/brimcap/brimcap-cli.ts:72]: This can go sideways if `this.binPath` or any `opts` value contains a quotation mark (very unlikely but possible). Make it bulletproof by switching from `execSync` to `spawnSync`!
